wcsprint.pl/public_python/pages/urls.py
from django.urls import path

from pages import views

app_name = "pages"

urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('about-me/', views.about_me, name='about_me'),
    path('services/', views.services, name='services'),
    path('gallery/', views.gallery, name='gallery'),
    path('form_app_save/', views.form_app_saving, name='form_app_save'),
    path('toilets/', views.toilets, name='toilets'),
    path('toilet_furniture/', views.toilet_furniture, name='toilet_furniture'),
    path('shower_cabins/', views.shower_cabins, name='shower_cabins'),
    path('welcome_site/',views.welcome,name='welcome'),
    path('mobile_index/',views.mobile_index,name='mobile_index'),
    path('mobile_about_me',views.mobile_about_me,name='mobile_about_me'),



	

]

wcsprint.pl/public_python/public_python/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

wcsprint.pl/public_python/pages/models.py
from django.db import models


# Create your models here.py


#class Gallery(models.Model):
#    img_title = models.CharField(max_length=100)
#    img_desc = models.CharField(max_length=500)
#    image = models.ImageField(upload_to='home/')


# class Applications(models.Model):
#     full_name = models.TextField()
#     added_time = models.TimeField()
#     phone_number = models.IntegerField()
#     email = models.EmailField()
#     application_type = models.ForeignKey(ApplicationType, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return f"ID number : {self.id} "

wcsprint.pl/public_python/pages/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.



def welcome(request):
    return render(
        request,
        'pages/welcome_site.html'
    )


def index(request):
    return render(
        request,
        'pages/index.html'
    )


def about_me(request):
    return render(
        request,
        'pages/about_me.html'
    )


def services(request):
    return render(
        request,
        'pages/services.html'
    )


def gallery(request):
    return render(
        request,
        'pages/gallery.html',

    )



def contact(request):
    return render(
        request,
        'pages/contact.html'
    )


def toilets(request):
    return render(
        request,
        'pages/toilets.html'
    )


def toilet_furniture(request):
    return render(
        request,
        'pages/toilet_furniture.html'
    )


def shower_cabins(request):
    return render(
        request,
        'pages/shower_cabins.html'
    )


def form_app_saving(request):
    if request.method == 'POST':
        full_name = request.POST['full_name']
        phone_number = request.POST['phone_number']
        # service = request.POST['service']
        email = request.POST['email']

        subject = 'New order'
        message = f'Prośba o kontakt od osoby - {full_name}, \n' \
                  f'numer telefonu - {phone_number} \n' \
                  f'email - {email} \n'

        if subject and message:
            try:
                send_mail(subject, message, email, ['wcsprint@wp.pl'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect('/pages/form_app_save')
        else:
            # In reality we'd use a form class
            # to get proper validation errors.
            return HttpResponse('Make sure all fields are entered and valid.')

    return render(request, 'pages/form_app_save.html')


def mobile_index(request):
    return render(
        request,
        'pages/mobile_index.html'
    )


def mobile_about_me(request):
    return render(
        request,
        'pages/mobile_about_me.html'
    )

wcsprint.pl/public_python/pages/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet" type="text/css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" rel="stylesheet" type="text/css">


    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>


    <style>

        body {
	
            background-image: url("/static/jpg/menu.jpg");

            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
    </style>


    <title>{% block tytuł %}

        WC SERWIS - Site

        {% endblock %}</title>


</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container">

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'pages:index' %}">MENU</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:about_me' %}">PORTFOLIO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">INNE USŁUGI</a>
                    <ul class="dropdown">
                        <li><a>naprawa wanien </a></li>
                        <li><a>armatura sanitarna</a></li>
                        <li><a>uprawnienia elektryczne</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:gallery' %}">GALERIA</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:contact' %}">KONTAKT</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


{% block ciało %}


{% endblock %}


</body>
</html>

wcsprint.pl/public_python/pages/templates/pages/about_me.html
{% extends 'pages/layout.html' %}





{% block ciało %}

            <div class="about_me">
                NAZYWAM SIĘ PRZEMYSŁAW SKOCZYLAS,<br>
                OD PIĘTNASTU LAT PRACUJĘ W BRANŻY SANITARNEJ.<br>
                JESTEM AUTORYZOWANYM SERWISANTEM MAREK:<br>
                -ROCA,<br>
                -INVENA,<br>
                -OMNIRES,<br>
                -POLL-SPA.<br>
                PROWADZĘ SERWIS POGWARANCYJNY DLA FIRM:<br>
                -GEBERIT,<br>
                -CERSANIT,<br>
                -KOŁO.<br>
                W RAZIE JAKICHKOLWIEK PYTAŃ PROSZĘ O KONTAKT -
                <a href="{% url 'pages:contact' %}"> TUTAJ</a>

            </div>

</html>



<style>
        body {
            background-image: url(http://www.wcsprint.pl/static/jpg/toilet_aboutme.jpg);
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }

</style>

{% endblock %}

wcsprint.pl/public_python/pages/templates/pages/contact.html
{% extends 'pages/layout.html' %}

{% block ciało %}


<div class="contact_me">
   CHĘĆ KONTAKTU?  <br>
   PROSZĘ WYPEŁNIĆ FORMULARZ
    <!--    WYPEŁNIJ PROSZĘ FORMULARZ:-->

    <br/>
</div>

<form action="{% url 'pages:form_app_save' %}" method="post">
    {% csrf_token %}

    <div class="form-group">
        <input type="text" name="full_name" class="form-control" placeholder="IMIĘ I NAZWISKO" required>
        <input type="number" name="phone_number" class="form-control" placeholder="NUMER TELEFONU" required>
        <input type="email" name="email" class="form-control" placeholder="E-MAIL" required>
    </div>
    <button type="submit" class="btn btn-primary">PRZEŚLIJ</button>
</form>


<div class="number"> KONTAK TELEFONICZNY NA NUMER : <br>
    531943741


</div>
<style>
    body {
        background-image: url(http://www.wcsprint.pl/static/jpg/contact_site.jpg);
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }
</style>


{% endblock ciało %}

</html>


<style>

</style>

wcsprint.pl/public_python/pages/templates/pages/form_app_save.html
{% extends 'pages/layout.html' %}


{% block ciało %}


                <div class="thanks">
                       <h1>Dziękuję za przesłanie danych kontaktowych</h1>

                </div>

<style>

</style>

{% endblock %}

wcsprint.pl/public_python/pages/templates/pages/gallery.html
{% extends 'pages/layout.html' %}
{% block ciało %}

<body>



<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>


<img alt="meble " src="http://www.wcsprint.pl/static/jpg/gallery/meble_.jpg" style="height:900px; width:1200px;">


<hr>
<hr>
<hr>

<img alt="meble 2" src="http://www.wcsprint.pl/static/jpg/gallery/meble_2.jpg">

<hr>
<hr>
<hr>


<img alt="zawor" src="http://www.wcsprint.pl/static/jpg/kabina_.jpg">




<hr>
<hr>
<hr>

<img alt="kabina prysznicowa" src="http://www.wcsprint.pl/static/jpg/gallery/kabina_2.jpg">


<hr>
<hr>
<hr>


<img alt="prysznic" src="http://www.wcsprint.pl/static/jpg/shower_info.jpg">


<hr>
<hr>
<hr>

<img alt="meble 3" src="http://www.wcsprint.pl/static/jpg/gallery/meble_3.jpg">

<hr>
<hr>
<hr>

<img alt="wc kompakt" src="http://www.wcsprint.pl/static/jpg/gallery/wc_kompakt.jpg">



<hr>
<hr>
<hr>


<img alt="zawor" src="http://www.wcsprint.pl/static/jpg/zawor.jpg">



</body>
</html>


<style>
    body {
        background-image: url(http://www.wcsprint.pl/static/jpg/la.jpg);
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }
</style>
{% endblock %}

wcsprint.pl/public_python/pages/templates/pages/index.html
{% extends 'pages/layout.html' %}
{% load static %}

{% block ciało %}

<div class="carousel slide" data-ride="carousel" id="carouselExampleIndicators">
    <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#carouselExampleIndicators"></li>
        <li data-slide-to="1" data-target="#carouselExampleIndicators"></li>
        <li data-slide-to="2" data-target="#carouselExampleIndicators"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
           <img alt="Second slide" class="d-block custom-width"
                 src="{% static 'jpg/wc_.jpg' %}">
            <div class="carousel-caption d-none d-md-block">
                <h5 class="animated zoomIn" style="animation-delay: 1s">TOALETY WC </h5>
                <!--                <p class="animated fadeInLeft" style="animation-delay: 2s">KOMPLEKSOWY MONTAŻ  TOALET KOMPAKTOWYCH ORAZ-->
                <!--                    PODTYNKOWYCH <br>-->

                <!--                </p>-->
                <p class="animated zoomIn" style="animation-delay: 3s"><a href="{% url 'pages:toilets' %}">WIĘCEJ
                    INFORMACJI</a></p>
            </div>
        </div>
        <div class="carousel-item">
            <img alt="Second slide" class="d-block custom-width"
                 src="{% static 'jpg/kabina_.jpg' %}">
            <div class="carousel-caption d-none d-md-block">
                <h5 class="animated zoomIn" style="animation-delay: 1s">KABINY PRYSZNICOWE</h5>
                <!--                <p class="animated fadeInLeft" style="animation-delay: 2s">MONTAŻ NOWYCH KABIN PRYSZNICOWYCH, NAPRAWA I WYMIANA STARYCH </p>-->
                <p class="animated zoomIn" style="animation-delay: 3s"><a href="{% url 'pages:shower_cabins' %}">WIĘCEJ
                    INFORMACJI</a></p>
            </div>
        </div>
        <div class="carousel-item">
            <img alt="Third slide" class="d-block custom-width" src="{% static 'jpg/meble_.jpg' %}">
            <div class="carousel-caption d-none d-md-block">
                <h5 class="animated zoomIn" style="animation-delay: 1s">MEBLE ŁAZIENKOWE</h5>
                <!--                <p class="animated fadeInLeft" style="animation-delay: 2s">MONTAŻ, WYMIANA MEBLI ŁAZIENKOWYCH</p>-->
                <p class="animated zoomIn" style="animation-delay: 3s"><a href="{% url 'pages:toilet_furniture' %}">WIĘCEJ
                    INFORMACJI</a></p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" data-slide="prev" href="#carouselExampleIndicators" role="button"><span
            aria-hidden="true" class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a
        class="carousel-control-next" data-slide="next" href="#carouselExampleIndicators" role="button"><span
        aria-hidden="true" class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>
</div>



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js">
</script>

{% endblock %}

wcsprint.pl/public_python/pages/templates/pages/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>

        body {
	
            background-image: url("/static/jpg/menu.jpg");

            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
    </style>


    <title>{% block tytuł %}

        WC SERWIS - Site

        {% endblock %}</title>


</head>
<body>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'pages:index' %}">MENU</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:about_me' %}">PORTFOLIO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">INNE USŁUGI</a>
                    <ul class="dropdown">
                        <li><a>naprawa wanien </a></li>
                        <li><a>armatura sanitarna</a></li>
                        <li><a>uprawnienia elektryczne</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:gallery' %}">GALERIA</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:contact' %}">KONTAKT</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-5">

{% block ciało %}


{% endblock %}

</div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

wcsprint.pl/public_python/pages/templates/pages/layout_mobile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" rel="stylesheet">


    <link rel="stylesheet" type="text/css" href=" {% static '/css/style.css' %} ">
    <style>

        body {
            background-image: url("/static/jpg/menu.jpg");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
    </style>


    <title>{% block tytuł %}

        WC SERWIS - Site

        {% endblock %}</title>


</head>


<body>
<!-- hamburger -->
<input type="checkbox" id="navi-toggle" class="checkbox"/>
<label for="navi-toggle" class="button">
    <span class="icon">&nbsp;</span>
</label>
<div class="background">&nbsp;</div>

<!-- nav -->
<nav class="nav">
    <ul class="list">
        <li class="item"><a class="link" href="{% url 'pages:mobile_index' %}"> Menu </a></li>
        <li class="item"><a class="link" href="{% url 'pages:mobile_about_me' %}"> Portfolio </a></li>    

 </ul>
</nav>

</body>


{% block ciało %}


{% endblock %}

wcsprint.pl/public_python/pages/templates/pages/mobile_about_me.html
{% extends 'pages/layout_mobile.html' %}


{% block ciało %}


<!--<div class="about_me_mobile">-->
<!--    -->
      <section>
    <h2>WC SPRINT</h2>
    <p> NAZYWAM SIĘ PRZEMYSŁAW SKOCZYLAS,<br>
    OD PIĘTNASTU LAT PRACUJĘ W BRANŻY SANITARNEJ.<br>
    JESTEM AUTORYZOWANYM SERWISANTEM MAREK:<br>
    -ROCCA,<br>
    -INVENA,<br>
    -OMNIRES,<br>
    -PULLSPA.<br>
    PROWADZĘ SERWIS POGWARANCYJNY DLA FIRM:<br>
    -GEBERIT,<br>
    -CERSANIT,<br>
    -KOŁO.<br>
    W RAZIE JAKICHKOLWIEK PYTAŃ PROSZĘ O KONTAKT -
    <a href="{% url 'pages:contact' %}"> TUTAJ</a>


    </p>
  </section>

<style>

</style>


{% endblock %}

wcsprint.pl/public_python/pages/templates/pages/services.html
{% extends 'pages/layout.html' %}
{% block ciało %}



<body>


    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
        <div class="carousel-inner">
    <div class="carousel-item active" >
      <img src="/app_przemek_website/pages/static/jpg/bathroom_1.jpg" class="d-block w-100" alt="KITCHEN IMAGE">
      <div class="carousel-caption d-none d-md-block ">
          <div class="carousel-text">


              KITCHEN TILES

          </div>

      </div>
    </div>
    <div class="carousel-item " >
      <img src="/app_przemek_website/pages/static/jpg/wc.jpg" class="d-block w-100" alt="OUTDOOR TILES">
      <div class="carousel-caption d-none d-md-block">

        <div class="carousel-text">
            OUTDOOR TILES
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/app_przemek_website/pages/static/jpg/wc_1.jpg" class="d-block w-100" alt="BATHROOM IMAGE">
      <div class="carousel-caption d-none d-md-block">

        <div class="carousel-text">
            BATHROOM TILES
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

    </body>

{% endblock ciało %}





</html>


<style>

</style>

wcsprint.pl/public_python/pages/templates/pages/shower_cabins.html
{% extends 'pages/layout.html' %}
{% block ciało %}

<body>
<div class="shower_info">
    MONTAŻ ORAZ WYMIANA: <br>
    <br>	
    -KABIN PRYSZNICOWYCH, <br>
    -KABIN WALK-IN, <br>
    -WANIEN,<br>
    -BRODZIKÓW WRAZ Z ZABUDOWĄ, <br>
    -SYFONÓW WANNOWYCH, BRODZIKOWYCH.



</div>


</body>
</html>


<style>
    body {
        background-image: url(http://www.wcsprint.pl/static/jpg/shower_info.jpg);
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }
</style>

{% endblock %}

wcsprint.pl/public_python/pages/templates/pages/toilet_furniture.html
{% extends 'pages/layout.html' %}
{% block ciało %}

    <body>

    <div class="furniture_info">

        MOŻLIWOŚĆ MONTAŻU:<br>
        -MEBLI ŁAZIENKOWYCH,<br>
        -UMYWALEK NABLATOWYCH,<br>
        -UMYWALEK WPUSZCZANYCH W BLAT,<br>
        -UMYWALEK ŚCIENNYCH,<br>
        -BATERII ŁAZIENKOWYCH.
    </div>

    </body>
</html>


<style>
   body {
        background-image: url(http://www.wcsprint.pl/static/jpg/furniture_info.jpg);
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }
</style>

{% endblock %}

wcsprint.pl/public_python/pages/templates/pages/toilets.html
{% extends 'pages/layout.html' %}
{% block ciało %}

    <body>
    <div class="toilets_info">
        PROWADZĘ KOMPLEKSOWE USŁUGI W ZAKRESIE TOALET.<br>
        MONTAŻ STELAŻY PODTYNKOWYCH ORAZ TOALET WOLNOSTOJĄCYCH.<br>
        MOŻLIWOŚĆ DEMONTAŻU STARYCH TOALET I WYMIANY NA NOWE.<br>
	PONADTO :<br>
        -NAPRAWA I WYMIANA ZAWORÓW, <br>
        -WYMIANA DESEK TOALETOWYCH (BOGATA OFERTA),<br>
        -PRZYCISKI DO STELAŻY PODTYNKOWYCH,<br>
	-ZAWORY DO WC PODTYNKOWYCH I  NATYNKOWYCH.







    </div>

    </body>
</html>


<style>
        body {
            background-image: url(http://www.wcsprint.pl/static/jpg/toilets_info.jpg);
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
</style>

{% endblock %}

wcsprint.pl/public_python/pages/templates/pages/welcome_site.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>

        body {
            background-image: url(/app_przemek_website/pages/static/jpg/menu.jpg);
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
    </style>

    <title>{% block tytuł %}

        WC SERWIS - Welcome Site

        {% endblock %}</title>
</head>
<body>
<div class="company__name">
    WC SPRINT<br>
    KOMPLEKSOWE USŁUGI SANITARNE
</div>

<a class="choose_site" href="{% url 'pages:index' %}">WERSJA NA KOMPUTER</a>
<br>

<a class="choose_site" href="{% url 'pages:about_me' %}">WERSJA MOBILNA</a>


</body>
</html>